# Makefile: A standard Makefile for hello.c

all: cowsrevenge

install:
	cp cowsrevenge /usr/local/bin/
	cp org.pipoypipagames.cowsrevenge.desktop /usr/share/applications
	cp org.pipoypipagames.cowsrevenge.appdata.xml /usr/share/metainfo/
	cp cowsrevenge_icon.png /usr/share/icons/hicolor/64x64/apps/
